name: databasebackuper
services:
  backupper:
    container_name: backupper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 12500
      DB_PORT: 5432
      DATABASE: public
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: 
      BACKUP_EVERY_2H: "false"
      BACKUP_EVERY_8H: "false"
      BACKUP_EVERY_24H: "true"
      BACKUP_WEEKLY: "false"
    volumes:
      - ./backups:/tmp
    ports:
      - 12500:12500
