# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

name: databasebackuper
services:
  backupper:
    container_name: backupper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 12500
      DB_PORT: 5432
      DATABASE: public
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: 
      BACKUP_FREQUENCY: 0 * * * *
    volumes:
      - ./backups:/tmp
    ports:
      - 12500:12500
    


